#ifndef ERRORS_H
#define ERRORS_H

enum class PingerResult {
    OK,
    ERR_CONFIGURATION_FILE_NOT_FOUND,
    ERR_CONFIGURATION_FILE_NOT_READABLE,
    ERR_CONFIGURATION_FILE_NOT_PARSEABLE,
    ERR_CONFIGURATION_FILE_EMPTY,
    ERR_CONFIGURATION_NOT_LOADED,
    ERR_CONFIGURATION_MISSING_TARGET_URL,
    ERR_CONFIGURATION_MISSING_AUTH_SECRET,
    ERR_CONFIGURATION_MISSING_PING_INTERVAL,
    ERR_CONFIGURATION_MISSING_PROCESS_TARGETS,
    ERR_CONFIGURATION_INVALID_PROCESS_TARGET,
    ERR_CONFIGURATION_GENERIC,

    ERR_NETWORK_INTERFACE_NOT_FOUND,
    ERR_NETWORK_INTERFACE_BAD_REQUEST,
    ERR_NETWORK_INTERFACE_GENERIC,
};

#endif //ERRORS_H
