name: C++ Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential ninja-build

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '6f29f12e82a8293156836ad81cc9bf5af41fe836'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Install dependencies with vcpkg
        run: |
          ${{ github.workspace }}/vcpkg/vcpkg install --triplet=x64-linux

      - name: Configure CMake
        run: |
          cmake -B ${{ github.workspace }}/build \
                -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DVCPKG_TARGET_TRIPLET=x64-linux \
                -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config Debug --parallel 4

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: ctest -C Debug --verbose